### ISSUE TITLE
Вопросы для обсуждения

### ISSUE THREAD

**Issue by Some-0ne-Else** [ivartm/bbbs#49]
**Решено** 1. Относительные пути для картинок (данные разрешаются относительно машины с запущенным фронтом).  
2. Что делать в случае не заполненных полей. Некоторые поля критичны для рендеринга приложения.
**Решено** 3. Набор данных для /main и /events отличается, в частности нет bool значения booked.
![image](https://user-images.githubusercontent.com/61430193/122757390-3cb49500-d2a0-11eb-80c3-3e1db16112d1.png)
![image](https://user-images.githubusercontent.com/61430193/122757578-72f21480-d2a0-11eb-851f-b0fffc1e548f.png)
**Решено** 4. В данных событий отказались от поля takenSeats теперь опираемся на одно значение?
![image](https://user-images.githubusercontent.com/61430193/122757728-a6cd3a00-d2a0-11eb-9496-f6f9fb6b2a4e.png)

**Comment by tanett** [comment]
В запросе профиле пользователя город теперь получаем объектом, в запросе на апдейт города из профиля ,в ответе нужно сделать так же : 
{
    "id": 1,
    "user": 1,
    "city": {
        "id": 2,
        "name": "Астрахань",
        "isPrimary": true
    }
}

**Comment by nkiryanov** [comment]
Решено!
